### ISSUE TITLE
Migrate to rxjava3

### ISSUE THREAD

**Issue by micHar** [FutureMind/rxwebsocket#2]

**Comment by vladp** [comment]
hello, I am just investigating the use of your library for our project.
Would like to use rxJava3 (this is a backend server, not android app) if possible.

Do you need help migrating ? (although I would not be able to test on android)

**Comment by micHar** [comment]
Hello @vladp. My main concern tbh was not the migration itself, but rather how to approach legacy rxjava2 which is still used in lots of projects. But I think we will just migrate and if rxjava2 is needed, we will provide a separate target or something like that. So if you created a PR, I would be happy to check if it works on Android and incorporate into the lib, thanks!

**Comment by vladp** [comment]
ok thank you. submitted PR.

**Comment by micHar** [comment]
Thanks @vladp!
